version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
    - "dtitov"
  ignore:
  - dependency-name: com.vaadin:vaadin-spring-boot-starter
    versions:
    - ">= 14.a"
    - "< 15"
  - dependency-name: com.vaadin:vaadin-spring-boot-starter
    versions:
    - ">= 15.a"
    - "< 16"
  - dependency-name: com.vaadin:vaadin-spring-boot-starter
    versions:
    - ">= 16.a"
    - "< 17"
  - dependency-name: org.vaadin.addons:aceeditor
    versions:
    - "> 0.8.15"
    - "< 1"
