language: python

python:
  - "3.6"

jdk:
  - oraclejdk8

cache:
  directories:
    - pip
    - $HOME/.m2

env:
  - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - pip install tavern

install: mvn install

before_script:
  - docker-compose up -d
  - sleep 30

script: py.test tests  -v

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker push nels/trackfind:latest;
    fi;
    if [ -n "$TRAVIS_TAG" ]; then
      docker tag nels/trackfind:latest nels/trackfind:$TRAVIS_TAG;
      docker push nels/trackfind:$TRAVIS_TAG;
    fi
