sudo: required

services:
  - docker

language: java

deploy:
  provider: releases
  api_key: "eacf5461d6f8947850056c829a7c8cc9cf2d3dac"
  file: target/trackfind-$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    tags: true

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t dtitov/trackfind:$TRAVIS_TAG .;
    docker push dtitov/trackfind:$TRAVIS_TAG;
    fi