sudo: required

services:
  - docker

language: java

deploy:
  provider: releases
  api_key:
    secure: fJMlgaNxZDRXFqNijbTGNkqME+kk+38C7IuOMKjr+U3UqBzMaV4z3iNUxgXFXyWdIT7PxVRHMBn6xMELU7R6r2rsHNbD+oaBu2505FjEgeeQzyMEH9NbTLu/diz/JSVfruwLlW2/Fr4uJPiGIQUc1CfRpZgsj2cIUFOGS3x2jkLKDpB3a2Le07/wA+rrFbnvou1Jj9CB1eptE/Gnsl70oC9IMrjxdSRq7+4i4mrdbVNsrC+4v/D6IJamE/OV7Cr6VvHVIGFd9fRSOQikt3sv5bz0PfqTM6gdl/nAsa8ZuANcRGSEmIpjPnl/9hi4nsy94O+/cvda+o3O0HJk1NGE4Z2ofvom+ffs+l5wB6D7qG2sEas89Ydv50x2rDE1Uafi4F00juIyx6V15S6oQ9WaIJ4YsgdTlbjaVq7oGz8XRnp/G1DTa1zadAYf5rmx9nVppiPuhmxGMRHRW08k0Eur6VEs5zJNFe8GCWHFgv9wFBVV4nc0BUy+AX1s+nZ54WMndaj/P+0UZe1ek4B+77r2/+HFKLvEbAvRRLoHhM3lfa5OYrZ15RwXGPCZrMTnUMwqpbPv/c2zrqHsqquwrIcTiaPLbsrPeDI5E9gAm5ukXns60gTcf5DAq75Ps/sbxgL9BHFwBY3UTwldFGYKVE1mOafFtoswq31w201Zv+5c0rQ=
  file: target/trackfind-$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    tags: true

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t dtitov/trackfind:$TRAVIS_TAG .;
    docker push dtitov/trackfind:$TRAVIS_TAG;
    fi