sudo: required

services:
  - docker

language: java

deploy:
  provider: releases
  api_key: "0690c710051d094751f2c9afdc6a72b17f78a705"
  file: target/trackfind-$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    tags: true

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t dtitov/trackfind:$TRAVIS_TAG .;
    docker push dtitov/trackfind:$TRAVIS_TAG;
    fi