version: "3"

services:

  db:
    image: postgres:10.5
    environment:
    - POSTGRES_DB=trackfind
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    volumes:
    - db:/var/lib/postgresql/data

  gsuite:
    image: nels/rest_gsuite:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  trackfind:
    image: nels/trackfind:latest
    ports:
    - "80:8888"
    depends_on:
    - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment:
    - DB_INSTANCE=db
    - POSTGRES_DB=trackfind
    - POSTGRES_USER
    - POSTGRES_PASSWORD

volumes:
  db:
