version: "3"

services:

  db:
    image: postgres:10.5
    environment:
    - POSTGRES_DB=trackfind
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    volumes:
    - db:/var/lib/postgresql/data

  trackfind:
    image: nels/trackfind:latest
    ports:
    - "8080:8080"
    depends_on:
    - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment:
    - SERVER_PORT=80
    - DB_INSTANCE=db
    - POSTGRES_DB=trackfind
    - POSTGRES_USER
    - POSTGRES_PASSWORD

volumes:
  db:
