version: "3"

services:

  db:
    image: postgres:10.5
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DB=trackfind
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    volumes:
    - trackfind-db:/var/lib/postgresql/data
    - db.sql:/docker-entrypoint-initdb.d/db.sql:ro

  trackfind:
    image: nels/trackfind:latest
    ports:
    - "8080:8080"
    depends_on:
    - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

volumes:
  trackfind-db:
