version: "3.7"

services:

  db:
    image: postgres:10.5
    environment:
      - POSTGRES_DB=trackfind
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data

  gsuite:
    image: nels/rest_gsuite:latest
    ports:
      - 8080:5000

  trackfind:
    image: nels/trackfind:latest
    init: true
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - TEST_ENV
      - DB_INSTANCE=db
      - POSTGRES_DB=trackfind
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  db:
