logging:
  level:
    org.springframework: ERROR
    com.vaadin: ERROR
    org.hibernate: ERROR
  file: console.log

server.port: 80

management.endpoints.web.exposure.include: "*"

spring:
  main.banner-mode: 'off'
  application.name: trackfind
  boot.admin:
    client:
      url: http://localhost:80/admin
      instance.service-url: http://localhost:80
    context-path: /admin
  jackson.serialization.indent-output: true
  datasource:
    url: jdbc:postgresql://${DB_INSTANCE:localhost}:${DB_PORT:5432}/${POSTGRES_DB:trackfind}?stringtype=unspecified
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud.refresh.refreshable: none

gsuite:
  listOfServers: ${GSUITE_SERVERS:gsuite:5000}
