logging:
  level:
    org.springframework: ERROR
    com.vaadin: ERROR
    org.hibernate: ERROR
  file: console.log

server:
  port: 8080
  use-forward-headers: true

management:
  endpoints.web.exposure.include: "*"
  metrics.export.influx:
    enabled: ${INFLUX_ENABLED:false}
    uri: ${INFLUX_URI:http://localhost:8086}
    user-name: ${INFLUX_USER}
    password: ${INFLUX_PASSWORD}
    db: ${INFLUX_DB:trackfind}
    step: ${INFLUX_STEP:10s}
  endpoint:
    jolokia:
      enabled: false

spring:
  application.name: TrackFind
  boot.admin:
    context-path: /admin
    client:
      url: http://localhost:8080/admin
      instance:
        name: TrackFind
        management-base-url: http://localhost:8080
        service-base-url: http://localhost:8080
  jackson.serialization.indent-output: true
  datasource:
    url: jdbc:postgresql://${DB_INSTANCE:localhost}:${DB_PORT:5432}/${POSTGRES_DB:trackfind}?stringtype=unspecified
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa.properties.hibernate.cache.use_second_level_cache: true
  jpa.properties.hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  cloud.refresh.refreshable: none

gsuite:
  listOfServers: ${GSUITE_SERVERS:gsuite:5000}

trackfind:
  admin: ${ADMIN_ELIXIR_ID}
  separator: ->
  scripting:
    language: CoffeeScript
    variables:
      input: input
      output: output
